### ISSUE TITLE
Line 56

### ISSUE THREAD

**Issue by pophilpo** [AlexKaravaev/ifmo#1]
Line 56 is written without any respect to PEP8 ( main.py)

**Comment by AlexKaravaev** [comment]
Dear @pophilpo. At least I don't play CS GO.

**Comment by pophilpo** [comment]
If you have 1930 hours in dota 2 you can't call yourself a developer or a student.

**Comment by AlexKaravaev** [comment]
Dear @pophilpo. Zavidui pliz molcha

**Comment by AlexKaravaev** [comment]
@pophilpo 
S
K
U
L
I

**Comment by pophilpo** [comment]
I admit it
I got wrecked.
Issue closed.
